syntax on
set number

" needed by pathogen for some arcane reason
set nocp

execute pathogen#infect()
filetype plugin indent on

set laststatus=2

" airline options

let g:airline#extensions#tabline#enabled = 1

" startify options

function! s:center_text(lines) abort
	let longest_line = max(map(copy(a:lines), 'len(v:val)'))
	let centered_lines = map(copy(a:lines), 'repeat(" ", (&columns / 2) - (longest_line / 2)) . v:val')
	return centered_lines
endfunction

let g:startify_bookmarks = ['~/dotfiles/vim/vimrc']
let g:startify_change_to_vcs_root = 1
let g:startify_custom_header = s:center_text(readfile($HOME . "/dotfiles/vim/header.txt"))
let g:startify_list_order = 	[['   Saved Sessions:',
				\ '   ---------------'], 'sessions',
				\ ['   Bookmarked Files',
				\  '   ----------------'], 'bookmarks',
				\ ['   Recently Used Files',
				\  '   -------------------'], 'files',
				\ ['   Current Directory',
				\  '   -----------------'], 'dir']
let g:startify_skiplist = ['\.git/.*']

" neocomplete options

let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_smart_case = 1
let g:neocomplete#sources#syntax#min_keyword_length = 3

if !exists('g:neocomplete#keyword_patterns')
	let g:neocomplete#keyword_patterns = {}
endif

let g:neocomplete#keyword_patterns['default'] = '\h\w*'

inoremap <expr><Left> neocomplete#close_popup() . "\<Left>"
inoremap <expr><Right> neocomplete#close_popup() . "\<Right>"
inoremap <expr><TAB> pumvisible() ? "\<C-n>" : "\<TAB>"

autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags

highlight Pmenu ctermbg=7 ctermfg=0
highlight PmenuSel ctermbg=1
highlight PmenuSbar ctermbg=0

