syntax on
set number

" needed by pathogen for some arcane reason
set nocp

execute pathogen#infect()
filetype plugin indent on

set laststatus=2

" airline options

let g:airline#extensions#tabline#enabled = 1

" startify options

function! s:center_text(lines) abort
	let longest_line = max(map(copy(a:lines), 'len(v:val)'))
	let centered_lines = map(copy(a:lines), 'repeat(" ", (&columns / 2) - (longest_line / 2)) . v:val')
	return centered_lines
endfunction

let g:startify_bookmarks = ['~/dotfiles/vim/vimrc']
let g:startify_change_to_vcs_root = 1
let g:startify_custom_header = s:center_text(readfile($HOME . "/dotfiles/vim/header.txt"))
let g:startify_list_order = 	[['   Saved Sessions:',
				\ '   ---------------'], 'sessions',
				\ ['   Bookmarked Files',
				\  '   ----------------'], 'bookmarks',
				\ ['   Recently Used Files',
				\  '   -------------------'], 'files',
				\ ['   Current Directory',
				\  '   -----------------'], 'dir']
let g:startify_skiplist = ['\.git/.*']


